Publish: Docs for using the keyring
astral-sh/uv pull request #8806
Opened 2024-11-04 10:16 UTC by konstin

While publishing from CI is clearly the better choice, for smaller projects it may just not be worth the effort, so we also support publishing from a local machine.

We don't support `.pypirc`, the non-standard file that saves password as plaintext to the user home. Instead, we recommend using the keyring for local publishing, using the operating system's much more secure, mostly standardized and better queryable credential store as backend. This comes with the catch that the keyring keys by URL+username, so we need to use the horrible query string attach to tag per-project scoped tokens to a more specific URL (https://github.com/pypa/twine/issues/565).

Fixes #7963

2024-11-04 10:22 UTC, j178 commented on docs/guides/publish.md
> +keyring set https://upload.pypi.org/legacy/?PACKAGE_NAME __token__
```suggestion
keyring set 'https://upload.pypi.org/legacy/?PACKAGE_NAME __token__'
```

2024-11-04 10:22 UTC, j178 commented on docs/guides/publish.md
> +uv publish --username __token__ --keyring-provider subprocess --publish-url https://upload.pypi.org/legacy/?PACKAGE_NAME
```suggestion
uv publish --username __token__ --keyring-provider subprocess --publish-url 'https://upload.pypi.org/legacy/?PACKAGE_NAME'
```

2024-11-04 10:27 UTC, konstin commented on docs/guides/publish.md
> +keyring set https://upload.pypi.org/legacy/?PACKAGE_NAME __token__
thanks!

2024-11-04 14:04 UTC, cthoyt requested changes
Given that the `?PACKAGE_NAME` suffix is a hack, I think it would also be beneficial to include in this guide the fact that you can have a single token for all publish URLs, and adding the hack is only an optional security precaution that allows you to have different tokens for different packages. I would suggest also including a section that says:

If you don't need the added security of having per-package tokens, you can use the following:

```shell
keyring set 'https://upload.pypi.org/legacy/' __token__
```

Then you can publish with:

```shell
uv publish --username __token__ --keyring-provider subprocess --publish-url 'https://upload.pypi.org/legacy/'
```

2024-11-04 14:04 UTC, cthoyt commented
Not to open up another can of worms, but what makes something standard or not? the `.pypirc` file is well-documented by the PyPA as a specification at https://packaging.python.org/en/latest/specifications/pypirc/

2024-11-04 20:21 UTC, zanieb commented
`.pypirc` is documented by the PyPA but isn't really a standard specification and the PyPA is warning people not to use it. Please use https://github.com/astral-sh/uv/issues/7676 for discussion on that topic.

2024-11-05 00:15 UTC, konstin commented
Personally, I find it misleading that `.pypirc` is in the specifications section of packaging.python.org next to the actual authoritative specs. As zanie said it has no PEP, it was added https://github.com/pypa/packaging.python.org/pull/734 amd it's a user guide and not a specification. The only mention in a PEP is a 2002(!) extension to distutils: https://github.com/python/peps/blob/0bb65f91d0eb1b087eee1c61d2bc446f421ab032/peps/pep-0301.rst?plain=1#L233.

I focussing the guide on security best practices, such as using the keyring with least-privileged tokens.

2025-04-28 12:50 UTC, closed without merging